#!/usr/bin/env python3
"""Generate static oEmbed JSON per article — ``/oembed/<slug>.json``.

oEmbed lets services like Notion, Discord, Slack, WordPress, Hugo and
the Atlassian suite render a rich preview of a URL the user paste-
shares. We emit it as a STATIC JSON file (build-time generation
pattern from `~/Drop/editorial-overhaul-plan.md` §4 WS5) so the file
is served by GitHub Pages with zero Cloudflare Worker invocations —
oEmbed clients never reach the dynamic edge.

Each article's `<head>` carries an oEmbed discovery link injected
elsewhere by postbuild::

    <link rel="alternate"
          type="application/json+oembed"
          href="https://sebastienrousseau.com/oembed/<slug>.json"
          title="<title>">

Runs after the article pages have been generated by ssg + postbuild,
so we can read each built article's frontmatter from disk.

Output: ``public/oembed/<slug>.json`` per dated post.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PUBLIC = ROOT / "public"
POSTS = ROOT / "_posts"

_BASE_URL = "https://sebastienrousseau.com"
_AUTHOR_NAME = "Sebastien Rousseau"
_AUTHOR_URL = "https://sebastienrousseau.com/about/"
_DATED_SLUG_RE = re.compile(r"^\d{4}-\d{2}-\d{2}-")
_TITLE_FM_RE = re.compile(r'^title:\s*"?([^"\n]+?)"?\s*$', re.MULTILINE)
_EXCERPT_FM_RE = re.compile(r'^excerpt:\s*"?([^"\n]+?)"?\s*$', re.MULTILINE)
_BANNER_FM_RE = re.compile(r'^banner:\s*"?([^"\n]+?)"?\s*$', re.MULTILINE)

# Default image when frontmatter has no banner — site brand image.
_DEFAULT_THUMBNAIL = (
    "https://cloudcdn.pro/clients/sebastienrousseau/v1/og/sebastienrousseau.png"
)
_THUMBNAIL_W = 1200
_THUMBNAIL_H = 630
_EMBED_HEIGHT = 240


def _esc_html(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _post_meta(path: Path) -> tuple[str, str, str, str] | None:
    text = path.read_text(encoding="utf-8", errors="ignore")
    title_m = _TITLE_FM_RE.search(text)
    if not title_m:
        return None
    excerpt_m = _EXCERPT_FM_RE.search(text)
    banner_m = _BANNER_FM_RE.search(text)
    return (
        title_m.group(1),
        path.stem,
        excerpt_m.group(1) if excerpt_m else "",
        banner_m.group(1) if banner_m else _DEFAULT_THUMBNAIL,
    )


def _embed_html(title: str, slug: str, excerpt: str) -> str:
    """The `html` payload — a single-line <blockquote> with the title,
    excerpt, and a link to the canonical URL. The receiving service
    typically renders this as-is OR uses the metadata to lay out its
    own card; either way the snippet is self-contained."""
    safe_title = _esc_html(title)
    safe_excerpt = _esc_html(excerpt)
    url = f"{_BASE_URL}/{slug}/"
    snippet = (
        f'<blockquote class="oembed-card">'
        f'<p><a href="{url}">{safe_title}</a></p>'
        + (f"<p>{safe_excerpt}</p>" if safe_excerpt else "")
        + f'<p><cite>{_AUTHOR_NAME} — sebastienrousseau.com</cite></p>'
        f"</blockquote>"
    )
    return snippet


def _oembed_doc(title: str, slug: str, excerpt: str, banner: str) -> dict:
    return {
        # spec: https://oembed.com/
        "version": "1.0",
        "type": "rich",
        "title": title,
        "author_name": _AUTHOR_NAME,
        "author_url": _AUTHOR_URL,
        "provider_name": "Sebastien Rousseau",
        "provider_url": _BASE_URL + "/",
        "thumbnail_url": banner,
        "thumbnail_width": _THUMBNAIL_W,
        "thumbnail_height": _THUMBNAIL_H,
        "html": _embed_html(title, slug, excerpt),
        "width": 600,
        "height": _EMBED_HEIGHT,
        "cache_age": 86400,
    }


def _write_oembed_files() -> int:
    out_dir = PUBLIC / "oembed"
    out_dir.mkdir(parents=True, exist_ok=True)
    written = 0
    for path in sorted(POSTS.glob("*.md")):
        if not _DATED_SLUG_RE.match(path.name):
            continue
        meta = _post_meta(path)
        if not meta:
            continue
        title, slug, excerpt, banner = meta
        doc = _oembed_doc(title, slug, excerpt, banner)
        (out_dir / f"{slug}.json").write_text(
            json.dumps(doc, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        written += 1
    return written


def main() -> int:
    written = _write_oembed_files()
    print(f"build_oembed: wrote {written} static oEmbed JSON file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
