"""Per-page social furniture: share rail, syndication (LinkedIn) panel, reuse
panel, action rail, oEmbed link, and byline strap.

Split from article_furniture (Phase 4.1). Imports shared author/URL constants,
regexes, and SVG glyphs from article_furniture and _labels from _i18n
(one-directional — article_furniture does not import this module).
"""

from __future__ import annotations

import re
import sys
from html import escape as _esc
from html import unescape as _unesc
from pathlib import Path
from urllib.parse import quote as _url_quote

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "lib"))
from _svg_icons import (
    _CARD_SVG_EMAIL as _SVG_EMAIL,
)
from _svg_icons import (
    _CARD_SVG_FB as _SVG_FB,
)
from _svg_icons import (
    _CARD_SVG_LI as _SVG_LI,
)
from _svg_icons import (
    _CARD_SVG_X as _SVG_X,
)
from postbuild_lib._i18n import _labels
from postbuild_lib.article_furniture import (
    _AUTHOR_FIRST,
    _AUTHOR_LAST,
    _BASE_URL,
    _CANONICAL_RE,
    _DESCRIPTION_RE,
    _LI_CONTENT_RE,
    _LICENSE_DEFAULT,
    _LICENSE_URLS,
    _MAIN_RE,
    _OG_TITLE_RE,
    _SVG_BLUESKY,
    _SVG_DOWNLOAD,
    _SVG_WA,
    _WRAP_CLOSE_RE,
    AUTHOR_NAME,
    AUTHOR_URL,
    _is_french,
)
from postbuild_lib.seo import _keywords_re


def inject_oembed_link(html: str) -> str:
    """Inject the `<link rel="alternate" type="application/json+oembed">`
    discovery link in the article's `<head>`. The href points at the
    static `/oembed/<slug>.json` file generated by
    `scripts/generators/build_oembed.py`. BlogPosting pages only;
    idempotent."""
    if '"@type":"BlogPosting"' not in html:
        return html
    if 'application/json+oembed' in html:
        return html
    canonical_m = _CANONICAL_RE.search(html)
    title_m = _OG_TITLE_RE.search(html)
    if not (canonical_m and title_m):
        return html
    url = canonical_m.group(1)
    # Strip /index.html, then drop the leading site domain to get the
    # bare slug. Canonicals look like https://sebastienrousseau.com/
    # <slug>/index.html or https://…/<slug>/.
    if url.endswith("/index.html"):
        url = url[: -len("/index.html")] + "/"
    bare = url.rstrip("/").rsplit("/", 1)[-1] or None
    if not bare:
        return html
    title = _unesc(title_m.group(1))
    oembed_href = f"{_BASE_URL}/oembed/{bare}.json"
    link = (
        f'<link rel="alternate" type="application/json+oembed" '
        f'href="{_esc(oembed_href, quote=True)}" '
        f'title="{_esc(title, quote=True)}">'
    )
    return html.replace("</head>", f"{link}</head>", 1)
_LEAD_TAKEAWAYS_RE = re.compile(
    r'<ul\s+class="post-lead-takeaways">(.*?)</ul>', re.IGNORECASE | re.DOTALL
)
_HTML_TAGS_RE = re.compile(r'<[^>]+>')
_BODY_QUESTION_RE = re.compile(r'<p(?:\s[^>]*)?>([^<]{50,300}?\?)\s*</p>', re.IGNORECASE)
def _byline_role(is_fr: bool) -> str:
    return "FONDATEUR · INGÉNIEUR" if is_fr else "FOUNDER · ENGINEER"
def inject_byline_strap(html: str) -> str:
    """Render an FT-style byline strap (``NAME · ROLE`` in caps) at the
    foot of the article body, INSIDE the wrap-div so it ends up
    immediately before the prev/next pagination (which the later
    ``inject_prev_next_nav`` pass anchors on ``</div>\\s*</main>``).
    The strap signals the editorial credit attached to the foregoing
    piece — the same gesture FT Professional uses to close a Features
    post. BlogPosting pages only; idempotent."""
    if '"@type":"BlogPosting"' not in html:
        return html
    if 'class="byline-strap"' in html:
        return html
    labels = _labels(html)
    is_fr = _is_french(html)
    author_url = "/fr/a-propos/index.html" if is_fr else AUTHOR_URL
    role = _byline_role(is_fr)
    aria = _esc(labels.get("Byline", "Byline"), quote=True)
    strap = (
        f'<p class="byline-strap" aria-label="{aria}">'
        f'<a href="{author_url}">{_esc(AUTHOR_NAME.upper())}</a>'
        f' <span class="sep" aria-hidden="true">·</span> '
        f"<span>{_esc(role)}</span></p>"
    )
    return _WRAP_CLOSE_RE.sub(strap + r"\1", html, count=1)
def _share_li(href: str, label: str, glyph: str) -> str:
    return (
        f'<li><a href="{_esc(href, quote=True)}" rel="noopener noreferrer" '
        f'aria-label="{_esc(label, quote=True)}">{glyph}</a></li>'
    )
def _strip_html_tags(text: str) -> str:
    return _unesc(_HTML_TAGS_RE.sub("", text)).strip()
def _extract_lead_takeaways_text(html: str) -> list[str]:
    """Return plain-text bullet strings from the lead block takeaways list."""
    m = _LEAD_TAKEAWAYS_RE.search(html)
    if not m:
        return []
    items = []
    for li in _LI_CONTENT_RE.findall(m.group(1)):
        text = _strip_html_tags(li)
        if text:
            items.append(text)
    return items[:5]
def _extract_body_question(html: str) -> str:
    """Return the first short question-paragraph found in the article body."""
    for m in _BODY_QUESTION_RE.finditer(html):
        text = _strip_html_tags(m.group(1)).strip()
        if text.endswith("?"):
            return text
    return ""
def _keywords_to_hashtags(html: str, max_n: int = 5) -> list[str]:
    """Convert JSON-LD BlogPosting keywords to #CamelCase hashtags."""
    m = _keywords_re.search(html)
    if not m or not m.group(1):
        return []
    seen: set[str] = set()
    result: list[str] = []
    for tag in m.group(1).split(","):
        tag = tag.strip()
        if not tag:
            continue
        words = tag.replace("-", " ").replace("_", " ").replace("/", " ").split()
        hashtag = "#" + "".join(w.capitalize() for w in words)
        if hashtag not in seen:
            seen.add(hashtag)
            result.append(hashtag)
        if len(result) >= max_n:
            break
    return result
def _generate_linkedin_post(
    payload: dict[str, str], html: str, labels: dict[str, str]
) -> str:
    """Build a copy-ready LinkedIn post from article metadata and lead block.

    Structure (mirrors the Readable Framework the editorial team uses):
      Hook      — article title on its own line
      Opening   — first 1-2 sentences of the meta description
      Takeaways — bullet list extracted from the lead block (3-5 items)
      CTA       — engagement question found in the body or a locale fallback
      Link note — placeholder for the first-comment link
      Footer    — canonical URL + CC-BY-4.0 attribution
      Hashtags  — up to 5 #CamelCase tags from JSON-LD keywords
    """
    url, title, desc = payload["url"], payload["title"], payload["desc"]

    # Opening: first two short sentences of the description, max ~220 chars
    sentences = desc.replace("—", "-").split(". ")
    opening = sentences[0].rstrip(".")
    if len(sentences) > 1 and len(opening) < 120:
        second = sentences[1].rstrip(".")
        if len(opening) + len(second) + 2 < 220:
            opening = f"{opening}. {second}"
    opening = opening.rstrip(".") + "."

    # Bullet takeaways from lead block
    takeaways = _extract_lead_takeaways_text(html)
    intro = labels.get("Syndicate.linkedin_intro", "Here are the key strategic takeaways:")
    bullets = "\n".join(f"- {t}" for t in takeaways)

    # Engagement question: first short question-paragraph in body, else label fallback
    question = _extract_body_question(html) or labels.get(
        "Syndicate.linkedin_question",
        "What is your organisation's approach to the challenges outlined in this piece?",
    )

    hashtags = " ".join(_keywords_to_hashtags(html))

    parts: list[str] = [title, "", opening]
    if takeaways:
        parts += ["", intro, "", bullets]
    parts += ["", question, "", f"→ {url}"]
    if hashtags:
        parts += ["", hashtags]
    parts += ["", "Sebastien Rousseau | CC-BY-4.0"]
    return "\n".join(parts)
def _share_payload(html: str) -> dict[str, str] | None:
    """Extract canonical URL + og:title + meta description and return
    the per-platform pre-fill strings the share rail needs. Returns
    None if canonical or title is missing."""
    url_m = _CANONICAL_RE.search(html)
    title_m = _OG_TITLE_RE.search(html)
    if not (url_m and title_m):
        return None
    url = url_m.group(1)
    # Strip the /index.html canonical suffix so previews carry a clean
    # trailing-slash URL — browsers resolve either.
    if url.endswith("/index.html"):
        url = url[: -len("/index.html")] + "/"
    title = _unesc(title_m.group(1))
    desc_m = _DESCRIPTION_RE.search(html)
    desc = _unesc(desc_m.group(1)) if desc_m else ""
    return {
        "url": url,
        "title": title,
        "desc": desc,
    }
def _share_rail_items(payload: dict[str, str], labels: dict[str, str]) -> str:
    """Render the 5 share-rail <li> anchors. Per-platform pre-fill
    strategy (the richer the prompt, the more likely the reader
    actually shares — empty share dialogs get closed):

    * **X** — 280 char limit; title + URL fits, description usually
      doesn't, so it's omitted and the OG meta card carries the
      visual preview.
    * **LinkedIn** — the share-offsite dialog ignores ``?text=`` today,
      so we open the feed composer (``?shareActive=true``) with
      title + description + URL pre-filled. That's the
      "Share your thoughts…" prompt the FT pattern lives in.
    * **Facebook** — stripped all ``?quote=`` support in 2017. Only
      the URL gets through; OG meta drives the preview card.
    * **WhatsApp + email** — no length cap, so they get the full
      title + description + URL share-card payload.
    """
    url, title, desc = payload["url"], payload["title"], payload["desc"]
    x_text = f"{title}\n\n{url}"
    wa_text = "\n\n".join(p for p in (title, desc, url) if p)
    email_body = "\n\n".join(p for p in (desc, f"Read more: {url}") if p)
    li_text = "\n\n".join(p for p in (title, desc, url) if p)
    enc_url = _url_quote(url, safe="")
    enc_title = _url_quote(title, safe="")
    return (
        _share_li(
            f"https://twitter.com/intent/tweet?text={_url_quote(x_text, safe='')}",
            labels.get("Share.x", "Share on X"),
            _SVG_X,
        )
        + _share_li(
            f"https://www.linkedin.com/feed/?shareActive=true&text={_url_quote(li_text, safe='')}",
            labels.get("Share.linkedin", "Share on LinkedIn"),
            _SVG_LI,
        )
        + _share_li(
            f"https://www.facebook.com/sharer/sharer.php?u={enc_url}",
            labels.get("Share.facebook", "Share on Facebook"),
            _SVG_FB,
        )
        + _share_li(
            f"https://wa.me/?text={_url_quote(wa_text, safe='')}",
            labels.get("Share.whatsapp", "Share on WhatsApp"),
            _SVG_WA,
        )
        + _share_li(
            f"mailto:?subject={enc_title}&body={_url_quote(email_body, safe='')}",
            labels.get("Share.email", "Share by email"),
            _SVG_EMAIL,
        )
        + _share_li(
            # Bluesky's compose intent accepts ?text= with title+URL —
            # 300 char post limit so we send title + URL like X.
            f"https://bsky.app/intent/compose?text={_url_quote(x_text, safe='')}",
            labels.get("Share.bluesky", "Share on Bluesky"),
            _SVG_BLUESKY,
        )
    )
def _syndication_payloads(
    payload: dict[str, str], html: str, labels: dict[str, str]
) -> dict[str, str]:
    """Return pre-formatted text payloads for platforms that don't
    accept ?text= compose intents — Medium (markdown import), Mastodon
    (no universal share URL across instances), LinkedIn (structured
    thought-leadership post). The reader copies and pastes into the
    platform of their choice."""
    url, title, desc = payload["url"], payload["title"], payload["desc"]
    # Medium import-style markdown — Medium's web importer reads the
    # first H1 + body. The canonical link goes at the top so the
    # Medium copy preserves the canonical URL.
    medium_md = "\n\n".join(
        p
        for p in (
            f"# {title}",
            f"> Originally published at [{url}]({url})",
            desc,
            f"Read the full article on sebastienrousseau.com: {url}",
        )
        if p
    )
    # Mastodon toot — 500 char limit on mastodon.social. Title +
    # truncated description + URL.
    desc_trunc = desc[:300].rstrip()
    if len(desc) > 300:
        desc_trunc += "…"
    mastodon = "\n\n".join(p for p in (title, desc_trunc, url) if p)
    linkedin = _generate_linkedin_post(payload, html, labels)
    return {"medium": medium_md, "mastodon": mastodon, "linkedin": linkedin}
def _render_syndication_panel(
    payload: dict[str, str], labels: dict[str, str], html: str
) -> str:
    """Inline collapsible at the article foot with copy buttons for
    Medium, Mastodon, and LinkedIn. Each pre block has a stable id so
    main.js's existing [data-copy] handler wires the clipboard."""
    payloads = _syndication_payloads(payload, html, labels)
    blocks = []
    label_map = {
        "medium": labels.get("Syndicate.medium", "Format for Medium"),
        "mastodon": labels.get("Syndicate.mastodon", "Format for Mastodon"),
        "linkedin": labels.get("Syndicate.linkedin", "Copy formatted for LinkedIn"),
    }
    copy_label = _esc(labels.get("Cite.copy", "Copy"))
    for key, body in payloads.items():
        target_id = f"syndicate-{key}"
        blocks.append(
            f'<div class="cite-format">'
            f"<h3>{_esc(label_map[key])}</h3>"
            f'<pre id="{target_id}">{_esc(body)}</pre>'
            f'<button type="button" class="copy-btn" data-copy="#{target_id}" '
            f'aria-label="{_esc(label_map[key], quote=True)} — {copy_label}">'
            f"{copy_label}</button>"
            f"</div>"
        )
    heading = _esc(labels.get("Syndicate.heading", "Syndicate this article"))
    return (
        f'<details class="cite-popover" id="syndicate-popover">'
        f"<summary>{heading}</summary>"
        + "".join(blocks)
        + "</details>"
    )
def inject_syndication_panel(html: str) -> str:
    """Append a syndication payload panel at the wrap-div close —
    pre-formatted blocks for Medium import, Mastodon, and LinkedIn,
    each with a copy button. Bluesky has a compose-intent URL so it
    joins the share rail directly; Medium, Mastodon, and LinkedIn have
    no universal share URL so the panel is the only path. BlogPosting
    pages only; idempotent."""
    if '"@type":"BlogPosting"' not in html:
        return html
    if 'id="syndicate-popover"' in html:
        return html
    payload = _share_payload(html)
    if payload is None:
        return html
    panel = _render_syndication_panel(payload, _labels(html), html)
    return _WRAP_CLOSE_RE.sub(panel + r"\1", html, count=1)
def inject_share_rail(html: str) -> str:
    """Render an FT-style vertical share rail (X / LinkedIn / Facebook
    / WhatsApp / email / Bluesky) at the top of the article body. CSS
    makes it ``position: sticky`` on >=64em and flows it inline on
    mobile. Anchors only — no inline JavaScript, CSP-safe.
    Medium / Mastodon payloads ship via inject_syndication_panel at
    the wrap-div close (no universal share URL). BlogPosting pages
    only; idempotent."""
    if '"@type":"BlogPosting"' not in html:
        return html
    if 'class="share-rail share-rail--sticky"' in html:
        return html
    payload = _share_payload(html)
    if payload is None:
        return html
    items = _share_rail_items(payload, _labels(html))
    aria = _esc(_labels(html).get("Share", "Share"), quote=True)
    rail = (
        f'<nav class="share-rail share-rail--sticky" aria-label="{aria}">'
        f"<ul>{items}</ul></nav>"
    )
    return _MAIN_RE.sub(rf"\1{rail}\2\3", html, count=1)
_LICENSE_RE = re.compile(r'<meta\s+name="license"\s+content="([^"]+)"', re.IGNORECASE)
_LICENSE_LABELS: dict[str, str] = {
    "CC-BY-4.0": "Creative Commons Attribution 4.0 International",
    "CC-BY-SA-4.0": "Creative Commons Attribution-ShareAlike 4.0 International",
    "CC-BY-NC-SA-4.0": "Creative Commons Attribution-NonCommercial-ShareAlike 4.0",
    "CC-BY-ND-4.0": "Creative Commons Attribution-NoDerivatives 4.0 International",
    "All-Rights-Reserved": "All rights reserved",
}
_SVG_QUOTE = (
    '<svg viewBox="0 0 16 16" aria-hidden="true" focusable="false">'
    '<path d="M3 4.5h3.5v3.5H5c0 1.5.5 2.5 1.5 3v1c-2 0-3.5-2-3.5-4V4.5zm6.5 0H13v3.5h-1.5'
    'c0 1.5.5 2.5 1.5 3v1c-2 0-3.5-2-3.5-4V4.5z"/>'
    "</svg>"
)
def _slug_from_canonical(html: str) -> str | None:
    """Return the bare slug from the canonical URL. Canonical URLs on
    this site always end with ``/<slug>/index.html``; strip that suffix
    before taking the last path segment so PDF / oEmbed routes get
    ``/api/pdf/<slug>.pdf`` and not ``/api/pdf/index.html.pdf``."""
    m = _CANONICAL_RE.search(html)
    if not m:
        return None
    url = m.group(1)
    for suffix in ("/index.html", "/"):
        if url.endswith(suffix):
            url = url[: -len(suffix)]
            break
    return url.rsplit("/", 1)[-1] or None
def _license_id(html: str) -> str:
    m = _LICENSE_RE.search(html)
    if m:
        candidate = m.group(1).strip()
        if candidate in _LICENSE_LABELS:
            return candidate
    return _LICENSE_DEFAULT
def inject_action_rail(html: str) -> str:
    """Render the floating ``.action-rail--sticky`` with Save PDF + Cite
    at the top of the article body. The CSS positions it on the right
    edge on >=64em viewports and as a sticky bottom bar on <48em.

    Save PDF is an anchor to ``/api/pdf/<slug>.pdf`` — the Cloudflare
    Worker (workers/pdf-proxy.js) forwards to the Fly.io WeasyPrint
    service and Edge-caches the response immutable for 24h. The
    ``download`` attribute hints the browser to save rather than
    navigate. A ``data-print-fallback`` hook on the same anchor lets
    main.js fall back to ``window.print()`` if the route ever 503s
    (e.g. local dev without the Worker).

    Cite jumps to the popover. BlogPosting pages only; idempotent."""
    if '"@type":"BlogPosting"' not in html:
        return html
    if 'class="action-rail action-rail--sticky"' in html:
        return html
    slug = _slug_from_canonical(html)
    if not slug:
        return html
    labels = _labels(html)
    aria = _esc(labels.get("Action.aria", "Article actions"), quote=True)
    pdf_href = f"/api/pdf/{slug}.pdf"
    items = (
        f'<li><a href="{pdf_href}" download="{slug}.pdf" '
        f'data-print-fallback rel="alternate" type="application/pdf">'
        f'{_SVG_DOWNLOAD}'
        f'<span>{_esc(labels.get("Action.savePdf", "Save PDF"))}</span></a></li>'
        f'<li><a href="#cite-popover">{_SVG_QUOTE}'
        f'<span>{_esc(labels.get("Action.cite", "Cite"))}</span></a></li>'
    )
    rail = (
        f'<nav class="action-rail action-rail--sticky" aria-label="{aria}">'
        f"<ul>{items}</ul></nav>"
    )
    return _MAIN_RE.sub(rf"\1{rail}\2\3", html, count=1)
def inject_reuse_panel(html: str) -> str:
    """Append a republish / reuse panel at the wrap-div close: licence
    statement, machine-readable ``rel="license"`` link, attribution
    snippet in a ``<pre>``. License id comes from
    ``<meta name="license">`` (or defaults to CC-BY-4.0) and must be
    on the allow-list; unknown ids fall back to the default rather
    than emitting a broken licence URL. BlogPosting pages only;
    idempotent."""
    if '"@type":"BlogPosting"' not in html:
        return html
    if 'class="reuse"' in html:
        return html
    url_m = _CANONICAL_RE.search(html)
    title_m = _OG_TITLE_RE.search(html)
    if not (url_m and title_m):
        return html
    url = url_m.group(1)
    title = _unesc(title_m.group(1))
    license_id = _license_id(html)
    license_label = _LICENSE_LABELS[license_id]
    license_url = _LICENSE_URLS.get(license_id)
    labels = _labels(html)
    if license_url:
        license_a = f'<a rel="license" href="{license_url}">{_esc(license_label)}</a>'
    else:
        license_a = _esc(license_label)
    # Description for the visible share-card preview AND the multi-line
    # attribution payload. Falls back to "" when the article has no
    # meta description (rare; default articles do).
    desc_m = _DESCRIPTION_RE.search(html)
    desc = _unesc(desc_m.group(1)) if desc_m else ""
    # Same heading-skip-safe pattern as the cite popover: the panel's
    # <h2 id="reuse-heading"> ("Republish this article") IS the
    # section heading; the title preview is a strong paragraph, not
    # another h-level inside it.
    meta_block = (
        f'<header class="reuse-meta">'
        f'<p class="reuse-title"><strong>{_esc(title)}</strong></p>'
        + (f"<p>{_esc(desc)}</p>" if desc else "")
        + "</header>"
    )
    # Richer multi-line attribution so the pasted block reads as a
    # complete share card, not a one-liner. Title + description give
    # republishers immediate context; URL + author + licence carry
    # the legal attribution requirement. The visible URL drops the
    # /index.html canonical suffix so the share payload reads
    # naturally — browsers resolve either form.
    share_url = url[: -len("/index.html")] + "/" if url.endswith("/index.html") else url
    attribution_lines = [title]
    if desc:
        attribution_lines.extend(["", desc])
    attribution_lines.extend(
        [
            "",
            f"Originally published at {share_url} by {_AUTHOR_FIRST} {_AUTHOR_LAST}.",
            f"Licensed under {license_id}.",
        ]
    )
    attribution = "\n".join(attribution_lines)
    copy_label = _esc(labels.get("Reuse.copy", "Copy attribution"))
    panel = (
        f'<section class="reuse" aria-labelledby="reuse-heading">'
        f'<h2 id="reuse-heading">'
        f'{_esc(labels.get("Reuse.heading", "Republish this article"))}</h2>'
        + meta_block
        + f"<p>{_esc(labels.get('Reuse.license', 'This article is licensed under'))} "
        + f"{license_a}. "
        + f"{_esc(labels.get('Reuse.attribution', 'Republication requires attribution to the canonical URL.'))}</p>"
        + f'<pre id="reuse-attribution">{_esc(attribution)}</pre>'
        + '<button type="button" class="copy-btn" data-copy="#reuse-attribution" '
        + f'aria-label="{copy_label}">{copy_label}</button>'
        + "</section>"
    )
    return _WRAP_CLOSE_RE.sub(panel + r"\1", html, count=1)
