/**
 * ActivityPub blog actor — `sebastien@sebastienrousseau.com`.
 *
 * Exposes the four endpoints a static-site blog needs to be followable
 * from Mastodon / Bluesky bridges / other Fediverse software:
 *
 *   GET  /.well-known/webfinger?resource=acct:sebastien@sebastienrousseau.com
 *        → WebFinger document pointing to the Actor URL.
 *   GET  /actor
 *        → Person actor (JSON-LD), with publicKey + inbox + outbox URLs.
 *   GET  /outbox
 *        → OrderedCollection of the last 20 Article activities,
 *          one per published post on /api/agents/posts.json.
 *   POST /inbox
 *        → 202 Accepted, no-op. Starter scope acknowledges inbound
 *          activities (Follow, Like, Announce, Create) without
 *          processing them. Phase 3b will add HTTP-signature
 *          validation + a queue that surfaces follower counts.
 *
 * Wired into the Cloudflare Worker pipeline by lang-router.js: any
 * request whose pathname matches one of the four routes above is
 * delegated here BEFORE the locale-routing + CSP-header path.
 *
 * The publicKey embedded below is the live key the Worker advertises.
 * It is regenerated by the maintainer offline (ed25519 → PEM-encoded
 * RSA wrapper; ed25519 actors aren't yet universally supported in
 * Mastodon — RSA-2048 stays the federation default through 2026).
 * The private key never enters this repo or any CI environment.
 */

const ACTOR_USERNAME = 'sebastien';
const DOMAIN = 'sebastienrousseau.com';
const BASE = `https://${DOMAIN}`;
const ACTOR_URL = `${BASE}/actor`;
const INBOX_URL = `${BASE}/inbox`;
const OUTBOX_URL = `${BASE}/outbox`;
const PROFILE_URL = `${BASE}/about/`;
const ICON_URL = 'https://cloudcdn.pro/stocks/images/sebastien-rousseau.png';

const ACCT = `acct:${ACTOR_USERNAME}@${DOMAIN}`;

// Public half of the Worker's RSA-2048 signing key. Replace before federation
// goes live; see workers/README-activitypub.md for the offline keygen recipe.
// The placeholder here is structurally valid PEM (so JSON.parse + downstream
// clients won't reject the actor) but is not a real key.
const PUBLIC_KEY_PEM = [
  '-----BEGIN PUBLIC KEY-----',
  'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAplaceholderplaceholder',
  'placeholderplaceholderplaceholderplaceholderplaceholderplaceholder',
  'placeholderplaceholderplaceholderplaceholderplaceholderplaceholder',
  'placeholderplaceholderplaceholderplaceholderplaceholderplaceholder',
  'placeholderplaceholderplaceholderplaceholderplaceholderplaceholder',
  'placeholderplaceholderplaceholderplaceholderplaceholderplaceholder',
  'pwIDAQAB',
  '-----END PUBLIC KEY-----',
].join('\n');

export const AP_ROUTES = new Set(['/.well-known/webfinger', '/actor', '/inbox', '/outbox']);

// True when the embedded PUBLIC_KEY_PEM has been replaced with a real key —
// i.e. it no longer contains the literal "placeholder" sentinel that the
// audit-2026-06-10 short-circuit checks for. While false, every AP route
// returns 503 so we never advertise a cryptographically-useless actor to
// the Fediverse. Replace the PEM and this flips to true automatically.
export const HAS_REAL_KEY = !PUBLIC_KEY_PEM.includes('placeholder');

// 503 short-circuit body shared by every AP route while HAS_REAL_KEY is false.
// Retry-After 86400 (24 h) tells well-behaved crawlers to back off for a day.
export function activityPubServiceUnavailable() {
  return new Response(
    'ActivityPub temporarily unavailable — actor key not configured.\n',
    {
      status: 503,
      headers: {
        'retry-after': '86400',
        'content-type': 'text/plain; charset=utf-8',
        'cache-control': 'no-store',
      },
    },
  );
}

const JSON_AP = 'application/activity+json; charset=utf-8';
const JSON_JRD = 'application/jrd+json; charset=utf-8';

function jsonResponse(body, contentType, status = 200, extraHeaders = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'content-type': contentType,
      'cache-control': 'public, max-age=300, must-revalidate',
      'access-control-allow-origin': '*',
      ...extraHeaders,
    },
  });
}

export function webfinger(request) {
  const url = new URL(request.url);
  const resource = url.searchParams.get('resource');

  // Spec: respond 400 if resource is missing entirely.
  if (!resource) {
    return new Response('Missing resource parameter', { status: 400 });
  }

  // Accept `acct:sebastien@sebastienrousseau.com` and the bare `acct:sebastien`
  // form some Mastodon-compatible servers use during followers-discovery.
  const accepted = new Set([
    ACCT,
    `acct:${ACTOR_USERNAME}`,
    ACTOR_URL,
    PROFILE_URL,
  ]);
  if (!accepted.has(resource)) {
    return new Response('Unknown resource', { status: 404 });
  }

  const body = {
    subject: ACCT,
    aliases: [PROFILE_URL, ACTOR_URL],
    links: [
      { rel: 'http://webfinger.net/rel/profile-page', type: 'text/html', href: PROFILE_URL },
      { rel: 'self', type: 'application/activity+json', href: ACTOR_URL },
      { rel: 'http://webfinger.net/rel/avatar', type: 'image/png', href: ICON_URL },
    ],
  };
  return jsonResponse(body, JSON_JRD);
}

export function actor() {
  const body = {
    '@context': [
      'https://www.w3.org/ns/activitystreams',
      'https://w3id.org/security/v1',
    ],
    id: ACTOR_URL,
    type: 'Person',
    preferredUsername: ACTOR_USERNAME,
    name: 'Sebastien Rousseau',
    summary:
      'Senior Banking Technologist writing on payments infrastructure, post-quantum cryptography, and AI in regulated finance.',
    url: PROFILE_URL,
    inbox: INBOX_URL,
    outbox: OUTBOX_URL,
    manuallyApprovesFollowers: false,
    discoverable: true,
    indexable: true,
    icon: { type: 'Image', mediaType: 'image/png', url: ICON_URL },
    publicKey: {
      id: `${ACTOR_URL}#main-key`,
      owner: ACTOR_URL,
      publicKeyPem: PUBLIC_KEY_PEM,
    },
  };
  return jsonResponse(body, JSON_AP);
}

/**
 * Build an OrderedCollection of Article activities from the build-time
 * posts JSON. The Worker fetches /api/agents/posts.json from the origin
 * (the same static endpoint `build_agent_api.py` writes on every build)
 * and transforms each entry into a minimal Create / Article activity.
 */
export async function outbox(request, fetchOrigin = fetch) {
  let posts = [];
  try {
    const resp = await fetchOrigin(`${BASE}/api/agents/posts.json`, {
      headers: { accept: 'application/json' },
    });
    if (resp.ok) {
      const data = await resp.json();
      posts = Array.isArray(data?.posts) ? data.posts : Array.isArray(data) ? data : [];
    }
  } catch {
    posts = [];
  }

  // Latest 20, newest first; defensive against missing fields.
  const items = posts.slice(0, 20).map((p) => {
    const url = p.url || (p.slug ? `${BASE}/${p.slug}/` : ACTOR_URL);
    const published = p.date || p.published || new Date().toISOString();
    return {
      '@context': 'https://www.w3.org/ns/activitystreams',
      id: `${url}#create`,
      type: 'Create',
      actor: ACTOR_URL,
      published,
      to: ['https://www.w3.org/ns/activitystreams#Public'],
      cc: [`${ACTOR_URL}/followers`],
      object: {
        id: url,
        type: 'Article',
        url,
        name: p.title || p.name || '(untitled)',
        summary: p.description || p.summary || '',
        published,
        attributedTo: ACTOR_URL,
        to: ['https://www.w3.org/ns/activitystreams#Public'],
      },
    };
  });

  const body = {
    '@context': 'https://www.w3.org/ns/activitystreams',
    id: OUTBOX_URL,
    type: 'OrderedCollection',
    totalItems: items.length,
    orderedItems: items,
  };
  return jsonResponse(body, JSON_AP, 200, {
    // Outbox is cheap to regenerate per request; cache shorter than the
    // actor + webfinger which only change on key rotation.
    'cache-control': 'public, max-age=60, must-revalidate',
  });
}

export function inbox(request) {
  // Starter scope: accept POST, return 202 without processing.
  // GET on /inbox is undefined per the spec — return 405.
  if (request.method !== 'POST') {
    return new Response('Method Not Allowed', {
      status: 405,
      headers: { allow: 'POST' },
    });
  }
  return new Response(null, { status: 202 });
}

/**
 * Route dispatcher. Returns a Response for AP routes, or null for
 * pass-through (lang-router continues its locale + CSP handling).
 */
export async function tryActivityPub(request, fetchOrigin, hasRealKey = HAS_REAL_KEY) {
  const { pathname } = new URL(request.url);
  if (!AP_ROUTES.has(pathname)) return null;

  // Short-circuit while the actor key is the placeholder PEM. Once a real
  // RSA-2048 key replaces PUBLIC_KEY_PEM, HAS_REAL_KEY flips to true and
  // the dispatch path below runs. The hasRealKey parameter exists so tests
  // can exercise the dispatch path without rebuilding the module.
  if (!hasRealKey) return activityPubServiceUnavailable();

  // AP_ROUTES.has() above guarantees the pathname matches one of the four
  // branches below — no default needed (and adding one would be dead code
  // the coverage gate flags).
  if (pathname === '/.well-known/webfinger') return webfinger(request);
  if (pathname === '/actor') return actor();
  if (pathname === '/outbox') return outbox(request, fetchOrigin);
  return inbox(request);
}
